services:
  mu_fe:
    build:
      context: .
      args:
        mode: ${mu_fe_MODE:-prod}

    hostname: ${mu_fe_HOSTNAME:-mu_fe}

    environment:
      GRAPHQL_API: http://${mu_main_be_HOSTNAME:-localhost}:${mu_main_be_INTERNAL_PORT:-8008}/query

    ports:
      - ${mu_fe_EXPOSED_PORT:-80}:3000
